server:
  port: 2000
spring:
  application:
    name: @name@
  redis:
    host: localhost
    port: 6379
    database: 0
  profiles:
    active: @profiles@
eureka:
  client:
    service-url:
      defaultZone: @eureka.service@
    registry-fetch-interval-seconds: 30
  instance:
    prefer-ip-address: true
    #心跳时间
    lease-renewal-interval-in-seconds: 2
    #心跳时间阈值
    lease-expiration-duration-in-seconds: 10
logging:
  level:
    com.sunkang: debug

#开发环境
---
spring:
  config:
    activate:
      on-profile: dev

#测试环境
---
spring:
  config:
    activate:
      on-profile: test

#生产环境
---
spring:
  config:
    activate:
      on-profile: prd
