server:
  port: 8082
spring:
  application:
    name: @name@
  profiles:
    active: @profiles@
eureka:
  client:
    service-url:
      defaultZone: @eureka.service@
    registry-fetch-interval-seconds: 30
  instance:
    prefer-ip-address: true
    #心跳时间
    lease-renewal-interval-in-seconds: 2
    #心跳时间阈值
    lease-expiration-duration-in-seconds: 10



#开发环境
---
spring:
  config:
    activate:
      on-profile: dev
logging:
  level:
    com.sunkang: info

#测试环境
---
spring:
  config:
    activate:
      on-profile: test

#生产环境
---
spring:
  config:
    activate:
      on-profile: prd