server:
  port: 8021
rocketmq:
  name-server: 127.0.0.1:9876
  #生产者
  producer:
    group: test_group
    retry-times-when-send-async-failed: 5
  consumer:
    group: test_group
spring:
  profiles:
    active: @profiles@

#开发环境
---
spring:
  config:
    activate:
      on-profile: dev

#测试环境
---
spring:
  config:
    activate:
      on-profile: test

#生产环境
---
spring:
  config:
    activate:
      on-profile: dev


